# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamShop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DreamShop
  pod 'FontAwesomeIconFactory'
  pod 'UPCardsCarousel'
  
  pod 'FirebaseAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_auth.podspec"
  pod 'FirebaseStorageUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_storage.podspec"
  pod 'FirebaseFacebookAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_fb.podspec"
  pod 'FirebaseGoogleAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_ggl.podspec"
  pod 'FirebaseTwitterAuthUI', :podspec => "https://raw.githubusercontent.com/firebase/FirebaseUI-iOS/master/FirebaseUI_dev_tw.podspec"
  
  pod 'Firebase/Crash'
  pod 'MagicalRecord'
  pod 'RestKit'
  pod 'RestKit/Testing'
  pod 'Mobile-Buy-SDK'

  target 'DreamShopTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'OCMock'
  end

end
