# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DreamShop' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DreamShop
  pod 'FontAwesomeIconFactory'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Twitter'
  pod 'Firebase/Crash'
  pod 'MagicalRecord'
  pod 'RestKit'
  pod 'RestKit/Testing'
  pod 'Mobile-Buy-SDK'

  target 'DreamShopTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'OCMock'
  end

end
